apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-ml-model-app
spec:
  selector:
    matchLabels:
      app: docker-ml-model-api
  replicas: 2
  template:
    metadata:
      labels:
        app: docker-ml-model-api
    spec:
      containers:
      - name: docker-ml-model-api
        image: aspandiyarkumtor/dockerhub:test
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        