apiVersion: v1
kind: Service
metadata:
  name: incident-classifier-service
  namespace: ml-classifier
spec:
  selector:
    app: incident-classifier-pod
  ports:
    - port: 8082
      targetPort: 5000
  type: LoadBalancer